---
deployment:
  tasks:
    - export DEPLOYPATH=/home/swthreegreen/staging.sw3greenenergyservices.co.uk/wp-content/themes/sw3-theme/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R sw3-theme/* $DEPLOYPATH
